### ISSUE TITLE
API 从 camera2 切换到 camera1 NullPointerException

### ISSUE THREAD

**Issue by toutoumu** [troop/FreeDcam#125]
Process: troop.com.freedcam, PID: 19110
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.Camera$Parameters android.hardware.Camera.getParameters()' on a null object reference
                                                       at freed.cam.apis.camera1.CameraHolder.GetCameraParameters(CameraHolder.java:212)
                                                       at freed.cam.apis.camera1.parameters.ParametersHandler.LoadParametersFromCamera(ParametersHandler.java:87)
                                                       at freed.cam.apis.camera1.Camera1Fragment.onCameraOpen(Camera1Fragment.java:260)
                                                       at freed.cam.apis.camera1.cameraholder.CameraHolderLegacy.OpenCamera(CameraHolderLegacy.java:54)
                                                       at freed.cam.apis.camera1.Camera1Fragment.StartCamera(Camera1Fragment.java:196)
                                                       at freed.cam.apis.camera1.Camera1Fragment.surfaceCreated(Camera1Fragment.java:238)
                                                       at android.view.SurfaceView.updateWindow(SurfaceView.java:643)
                                                       at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:171)
                                                       at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2364)
                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1364)
                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6757)
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:923)
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:735)
                                                       at android.view.Choreographer.doFrame(Choreographer.java:667)
                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:909)
                                                       at android.os.Handler.handleCallback(Handler.java:755)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:156)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6524)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by toutoumu** [comment]
Android 7.0 huawei p9 
CameraHolderLegacy.java      private  Camera openWrapper(int n) 出错了  
line 75
catch (InvocationTargetException e) {
            Log.e(TAG, e.getMessage());   // e.getMessage() == null
            return Camera.open(n);}

**Comment by troop** [comment]
Does it support camera2 full?

**Comment by toutoumu** [comment]
这个bug已经不会出现了, 因为现在打开相机,不会调用到CameraHolderLegacy. openWrapper 方法,
但是在使用Log.e(TAG, e.getMessage()); 这行代码的时候要保证, e.getMessage() != null
