### ISSUE TITLE
Crash alpha12

### ISSUE THREAD

**Issue by rancidfrog** [troop/FreeDcam#142]
```
03-12 20:04:19.195 W/System.err(4928): java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 1, found: 78 Pager id: troop.com.freedcam:id/pager Pager class: class android.support.v4.view.ViewPager Problematic adapter: class freed.viewer.screenslide.ScreenSlideFragment$ScreenSlidePagerAdapter
03-12 20:04:19.195 W/System.err(4928): 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1167)
03-12 20:04:19.195 W/System.err(4928): 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
03-12 20:04:19.195 W/System.err(4928): 	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
03-12 20:04:19.195 W/System.err(4928): 	at android.view.View.measure(View.java:19857)
03-12 20:04:19.195 W/System.err(4928): 	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
03-12 20:04:19.195 W/System.err(4928): 	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
03-12 20:04:19.195 W/System.err(4928): 	at android.view.View.measure(View.java:19857)
03-12 20:04:19.195 W/System.err(4928): 	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1658)
03-12 20:04:19.196 W/System.err(4928): 	at android.view.View.measure(View.java:19857)
03-12 20:04:19.196 W/System.err(4928): 	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
03-12 20:04:19.196 W/System.err(4928): 	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
03-12 20:04:19.196 W/System.err(4928): 	at android.view.View.measure(View.java:19857)
03-12 20:04:19.196 W/System.err(4928): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
03-12 20:04:19.196 W/System.err(4928): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
03-12 20:04:19.196 W/System.err(4928): 	at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
03-12 20:04:19.196 W/System.err(4928): 	at android.view.View.measure(View.java:19857)
03-12 20:04:19.196 W/System.err(4928): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
03-12 20:04:19.196 W/System.err(4928): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
03-12 20:04:19.196 W/System.err(4928): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
03-12 20:04:19.196 W/System.err(4928): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
03-12 20:04:19.196 W/System.err(4928): 	at android.view.View.measure(View.java:19857)
03-12 20:04:19.196 W/System.err(4928): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
03-12 20:04:19.197 W/System.err(4928): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
03-12 20:04:19.197 W/System.err(4928): 	at android.view.View.measure(View.java:19857)
03-12 20:04:19.197 W/System.err(4928): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
03-12 20:04:19.197 W/System.err(4928): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
03-12 20:04:19.197 W/System.err(4928): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
03-12 20:04:19.197 W/System.err(4928): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
03-12 20:04:19.197 W/System.err(4928): 	at android.view.View.measure(View.java:19857)
03-12 20:04:19.197 W/System.err(4928): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
03-12 20:04:19.197 W/System.err(4928): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
03-12 20:04:19.197 W/System.err(4928): 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:689)
03-12 20:04:19.197 W/System.err(4928): 	at android.view.View.measure(View.java:19857)
03-12 20:04:19.197 W/System.err(4928): 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2275)
03-12 20:04:19.197 W/System.err(4928): 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1366)
03-12 20:04:19.197 W/System.err(4928): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1619)
03-12 20:04:19.198 W/System.err(4928): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
03-12 20:04:19.198 W/System.err(4928): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6343)
03-12 20:04:19.198 W/System.err(4928): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
03-12 20:04:19.198 W/System.err(4928): 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
03-12 20:04:19.198 W/System.err(4928): 	at android.view.Choreographer.doFrame(Choreographer.java:621)
03-12 20:04:19.198 W/System.err(4928): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
03-12 20:04:19.198 W/System.err(4928): 	at android.os.Handler.handleCallback(Handler.java:751)
03-12 20:04:19.198 W/System.err(4928): 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-12 20:04:19.198 W/System.err(4928): 	at android.os.Looper.loop(Looper.java:154)
03-12 20:04:19.198 W/System.err(4928): 	at android.app.ActivityThread.main(ActivityThread.java:6169)
03-12 20:04:19.198 W/System.err(4928): 	at java.lang.reflect.Method.invoke(Native Method)
03-12 20:04:19.198 W/System.err(4928): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
03-12 20:04:19.198 W/System.err(4928): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
--------- beginning of crash
03-12 20:04:19.200 E/AndroidRuntime(4928): FATAL EXCEPTION: main
03-12 20:04:19.200 E/AndroidRuntime(4928): Process: troop.com.freedcam, PID: 4928
03-12 20:04:19.200 E/AndroidRuntime(4928): java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 1, found: 78 Pager id: troop.com.freedcam:id/pager Pager class: class android.support.v4.view.ViewPager Problematic adapter: class freed.viewer.screenslide.ScreenSlideFragment$ScreenSlidePagerAdapter
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1167)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.view.View.measure(View.java:19857)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.view.View.measure(View.java:19857)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1658)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.view.View.measure(View.java:19857)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.view.View.measure(View.java:19857)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.view.View.measure(View.java:19857)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.view.View.measure(View.java:19857)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.view.View.measure(View.java:19857)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.view.View.measure(View.java:19857)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:689)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.view.View.measure(View.java:19857)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2275)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1366)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1619)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6343)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.view.Choreographer.doFrame(Choreographer.java:621)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.os.Handler.handleCallback(Handler.java:751)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.os.Looper.loop(Looper.java:154)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at android.app.ActivityThread.main(ActivityThread.java:6169)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at java.lang.reflect.Method.invoke(Native Method)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
03-12 20:04:19.200 E/AndroidRuntime(4928): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
03-12 20:04:19.308 I/OpenGLRenderer(617): Initialized EGL, version 1.4
03-12 20:04:19.309 D/OpenGLRenderer(617): Swap behavior 1
03-12 20:04:19.659 W/ActivityManager(617): Activity pause timeout for ActivityRecord{c8b989d u0 troop.com.freedcam/freed.cam.ActivityFreeDcamMain t1662}
03-12 20:04:19.805 I/ActivityManager(617): Displayed com.android.packageinstaller/.permission.ui.GrantPermissionsActivity: +146ms
03-12 20:04:19.818 W/SurfaceFlinger(887): couldn't log to binary event log: overflow.
03-12 20:04:21.866 W/ActivityManager(617):   Force finishing activity troop.com.freedcam/freed.cam.ActivityFreeDcamMain
03-12 20:04:21.908 I/ActivityManager(617): Killing 4928:troop.com.freedcam/u0a67 (adj 100): crash
```

**Comment by troop** [comment]
hmm thats worse nothing points direct to freedcam source

**Comment by petrica-celrau** [comment]
no such problem on redmi note 3 pro with LineageOS 13

**Comment by rancidfrog** [comment]
My mistake,
It happened because I revoked permissions to test new handler.
As I installed over last packaged and did not uninstall then install new alpha, which is why I had to revoke permission to test.

Just uninstalled and reinstalled, without any issues.

One note;
On first install the default picture size always is smallest resolution 160x120 and not highest resolution.
