### ISSUE TITLE
Crash log then first start, mi4c, android 7.0, v4.1.20

### ISSUE THREAD

**Issue by orelaa** [troop/FreeDcam#180]
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:318)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.NumberFormatException: For input string: "auto"
	at java.lang.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1306)
	at java.lang.Float.parseFloat(Float.java:459)
	at freed.cam.featuredetector.Camera1FeatureDetectorTask.getSupportedShutterValues(Camera1FeatureDetectorTask.java:473)
	at freed.cam.featuredetector.Camera1FeatureDetectorTask.detectManualExposureTime(Camera1FeatureDetectorTask.java:452)
	at freed.cam.featuredetector.Camera1FeatureDetectorTask.doInBackground(Camera1FeatureDetectorTask.java:176)
	at freed.cam.featuredetector.Camera1FeatureDetectorTask.doInBackground(Camera1FeatureDetectorTask.java:25)
	at android.os.AsyncTask$2.call(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more

**Comment by troop** [comment]
#151

**Comment by troop** [comment]
d305d46cb9000fadc37781d2c788242b47f0a896

**Comment by orelaa** [comment]
Can you fix it in the next version?
