### ISSUE TITLE
Broken camera2 support in redmi 3s

### ISSUE THREAD

**Issue by mohdmujahidansari526** [troop/FreeDcam#182]
App is force stopping itself if camera2api is enabled.
Here's the log...

java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
	at freed.utils.StringFloatArray.<init>(StringFloatArray.java:28)
	at freed.cam.apis.camera2.parameters.AeHandler$ManualExposureApi2.<init>(AeHandler.java:133)
	at freed.cam.apis.camera2.parameters.AeHandler.<init>(AeHandler.java:59)
	at freed.cam.apis.camera2.parameters.ParameterHandlerApi2.Init(ParameterHandlerApi2.java:117)
	at freed.cam.apis.camera2.Camera2Fragment$7.run(Camera2Fragment.java:206)
	at android.os.Handler.handleCallback(Handler.java:742)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by troop** [comment]
Need full log from featuredetector

**Comment by mohdmujahidansari526** [comment]
may i know how i get that?

**Comment by mohdmujahidansari526** [comment]
Okay here's the full log from the file created in FreedCam directory.
[log.txt](https://github.com/troop/FreeDcam/files/1066165/log.txt)

**Comment by Tynach** [comment]
I'm having the same problem in my Pixel phone. Attaching the log.
[log.txt](https://github.com/troop/FreeDcam/files/1066200/log.txt)

**Comment by troop** [comment]
Problem is gone?

**Comment by mohdmujahidansari526** [comment]
Yes. its working perfectly now. thanks
