### ISSUE TITLE
MyPhone Infinity IIS - raw option disappeared?

### ISSUE THREAD

**Issue by LosTigeros** [troop/FreeDcam#195]
Log:
https://gamecentrum.pl/own/FreeDcam/INFINITY_II_S/log.txt

Camera Parameters:
https://gamecentrum.pl/own/FreeDcam/INFINITY_II_S/INFINITY_II_S_CameraParameters.txt

DNGProfile:
https://gamecentrum.pl/own/FreeDcam/INFINITY_II_S/config/dngprofiles.xml

Phone Model:
MyPhone Infinity IIS

FreeDcam Version:
4.1 alpha24

Problem Description:
I no longer have option for making pictures in RAW, only bayer.
I dont know from which version it started, because i didn't had phone since two months.

**Comment by troop** [comment]
Reset the appsettings and it should appear

**Comment by LosTigeros** [comment]
Yep it shows now.
But there is a crash:
https://gamecentrum.pl/own/FreeDcam/INFINITY_II_S/2017.07.19-12.04.22-log.txt

**Comment by troop** [comment]
```
java.io.FileNotFoundException: /storage/emulated/0/DCIM/FreeDcam/IMG_2017_07_19_12_04_51.jpg: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:496)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
	at freed.cam.apis.basecamera.modules.BasePictureModule.saveJpeg(BasePictureModule.java:185)
	at freed.cam.apis.camera1.modules.PictureModuleMTK.onPictureTaken(PictureModuleMTK.java:99)
	at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1255)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
	at libcore.io.IoBridge.open(IoBridge.java:482)
	... 8 more

D:12.04.51:BasePictureModule:End Saving Bytes
D:12.04.52:PictureModuleMTK:Found Raw: Filesize: 15980544 File:/storage/sdcard0/DCIM/FreeDcam/mtk1500304588814pure__3264x2448_10_3.bayer
```

temporary workaround is to select the external sd and set the path to internal. then saving should work. 
i have no idea whats going wrong. that path is returned from Environment.getExternalStorageDirectory()

**Comment by LosTigeros** [comment]
Maybe you could just make a function for checking if
`Environment.getExternalStorageDirectory()` dir exists?

```
if (Environment.getExternalStorageDirectory().isDirectory()) { // returns true if exists and its a directory otherwise false
    return Environment.getExternalStorageDirectory();
} else {
    /** Check for directories like
       * /storage/sdcard0
       * /storage/emulated/legacy
       * /storage/emulated/0
       * /sdcard
       */
}
```

**Comment by LosTigeros** [comment]
Yup, correcting blacklevel fixes that.

**Comment by troop** [comment]
did latest alpha fix the viewer problem?

**Comment by LosTigeros** [comment]
Yes, its working fine now.

**Comment by LosTigeros** [comment]
Just saw it. On latest version dng files are empty 0 bytes files. Jpg are fine.

**Comment by troop** [comment]
Check if your dngprofiles contains <whitelevel>1023</whitelevel>
