### ISSUE TITLE
api2, somethings wrong with flash loading

### ISSUE THREAD

**Issue by troop** [troop/FreeDcam#3]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.hardware.camera2.CaptureRequest$Builder.get(android.hardware.camera2.CaptureRequest$Key)' on a null object reference
at com.troop.freedcam.camera2.parameters.modes.FlashModeApi2.GetValue(FlashModeApi2.java:41)
at com.troop.freedcam.i_camera.parameters.AbstractParameterHandler.setMode(AbstractParameterHandler.java:139)
at com.troop.freedcam.i_camera.parameters.AbstractParameterHandler.SetAppSettingsToParameters(AbstractParameterHandler.java:104)
at com.troop.freedcam.camera2.parameters.ParameterHandlerApi2.Init(ParameterHandlerApi2.java:63)
at com.troop.freedcam.camera2.BaseCameraHolderApi2$3.onOpened(BaseCameraHolderApi2.java:386)
at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:118)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5349)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)

dont understand that works on my g3 and nexus5.
seems my devices are not default lol

**Comment by troop** [comment]
was reported from yureka, xperia z3, htc_himaulatt,L-01F (g2),Nexus 5 (hammerhead)
