### ISSUE TITLE
java.lang.IllegalArgumentException: from g2

### ISSUE THREAD

**Issue by troop** [troop/FreeDcam#34]
java.lang.IllegalArgumentException: No view found for id 0x7f0b00cd (troop.com.freedcam:id/pager) for fragment ImageFragment{35968a65 #20 id=0x7f0b00cd}
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1059)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
	at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:163)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1106)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:952)
	at android.support.v4.view.ViewPager$3.run(ViewPager.java:251)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:549)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5349)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)

**Comment by troop** [comment]
![photo_2016-01-14_14-35-49](https://cloud.githubusercontent.com/assets/377693/12325683/24eb761a-bacc-11e5-8d27-90a1401dde36.jpg)

seems same problem
