### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException:  op2

### ISSUE THREAD

**Issue by troop** [troop/FreeDcam#38]
2016-01-20 09:23:52:--------- beginning of crash
2016-01-20 09:23:52:E/AndroidRuntime(19472): FATAL EXCEPTION: main
2016-01-20 09:23:52:E/AndroidRuntime(19472): Process: troop.com.freedcam, PID: 19472
2016-01-20 09:23:52:E/AndroidRuntime(19472): java.lang.ArrayIndexOutOfBoundsException: length=49; index=49
2016-01-20 09:23:52:E/AndroidRuntime(19472):    at com.troop.freedcam.camera2.parameters.manual.ManualExposureTimeApi2.SetValue(ManualExposureTimeApi2.java:104)
2016-01-20 09:23:52:E/AndroidRuntime(19472):    at com.troop.freedcam.i_camera.parameters.AbstractParameterHandler.setManualMode(AbstractParameterHandler.java:222)
2016-01-20 09:23:52:E/AndroidRuntime(19472):    at com.troop.freedcam.camera2.parameters.ParameterHandlerApi2.SetAppSettingsToParameters(ParameterHandlerApi2.java:198)
2016-01-20 09:23:52:E/AndroidRuntime(19472):    at com.troop.freedcam.camera2.parameters.ParameterHandlerApi2.Init(ParameterHandlerApi2.java:146)
2016-01-20 09:23:52:E/AndroidRuntime(19472):    at com.troop.freedcam.camera2.BaseCameraHolderApi2$4.onConfigured(BaseCameraHolderApi2.java:745)
2016-01-20 09:23:52:E/AndroidRuntime(19472):    at java.lang.reflect.Method.invoke(Native Method)
2016-01-20 09:23:52:E/AndroidRuntime(19472):    at java.lang.reflect.Method.invoke(Method.java:372)
2016-01-20 09:23:52:E/AndroidRuntime(19472):    at android.hardware.camera2.dispatch.InvokeDispatcher.dispatch(InvokeDispatcher.java:39)
2016-01-20 09:23:52:D/Orientierungs Korrektur:(23600): Set Value to:OFF
2016-01-20 09:23:52:E/AndroidRuntime(19472):    at android.hardware.camera2.dispatch.HandlerDispatcher$1.run(HandlerDispatcher.java:65)
2016-01-20 09:23:52:E/AndroidRuntime(19472):    at android.os.Handler.handleCallback(Handler.java:739)
2016-01-20 09:23:52:E/AndroidRuntime(19472):    at android.os.Handler.dispatchMessage(Handler.java:95)
2016-01-20 09:23:52:E/AndroidRuntime(19472):    at android.os.Looper.loop(Looper.java:135)
2016-01-20 09:23:52:E/AndroidRuntime(19472):    at android.app.ActivityThread.main(ActivityThread.java:5300)
2016-01-20 09:23:52:E/AndroidRuntime(19472):    at java.lang.reflect.Method.invoke(Native Method)
2016-01-20 09:23:52:E/AndroidRuntime(19472):    at java.lang.reflect.Method.invoke(Method.java:372)
2016-01-20 09:23:52:E/AndroidRuntime(19472):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
2016-01-20 09:23:52:E/AndroidRuntime(19472):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

**Comment by troop** [comment]
thats seems caused due the first log

2016-01-20 09:23:52:W/System.err(23600): java.lang.NullPointerException: Attempt to invoke virtual method 'void troop.com.themesample.views.ManualButton.SetAbstractManualParameter(com.troop.freedcam.i_camera.parameters.AbstractManualParameter)' on a null object reference
2016-01-20 09:23:52:W/System.err(23600):    at troop.com.themesample.subfragments.ManualFragmentRotatingSeekbar.setWrapper(ManualFragmentRotatingSeekbar.java:154)
2016-01-20 09:23:52:W/System.err(23600):    at troop.com.themesample.subfragments.ManualFragmentRotatingSeekbar.SetCameraUIWrapper(ManualFragmentRotatingSeekbar.java:138)
2016-01-20 09:23:52:W/System.err(23600):    at troop.com.themesample.subfragments.CameraUiFragment.onCreateView(CameraUiFragment.java:225)
2016-01-20 09:23:52:W/System.err(23600):    at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)
2016-01-20 09:23:52:W/System.err(23600):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1016)
2016-01-20 09:23:52:W/System.err(23600):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1197)
2016-01-20 09:23:52:W/System.err(23600):    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
2016-01-20 09:23:52:W/System.err(23600):    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1562)
2016-01-20 09:23:52:W/System.err(23600):    at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:330)
2016-01-20 09:23:52:W/System.err(23600):    at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:416)
2016-01-20 09:23:52:W/System.err(23600):    at android.app.Activity.performResume(Activity.java:6187)
2016-01-20 09:23:52:W/System.err(23600):    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3004)
2016-01-20 09:23:52:W/System.err(23600):    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3049)
2016-01-20 09:23:52:W/System.err(23600):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2421)
2016-01-20 09:23:52:W/System.err(23600):    at android.app.ActivityThread.access$900(ActivityThread.java:154)
2016-01-20 09:23:52:W/System.err(23600):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1322)
2016-01-20 09:23:52:W/System.err(23600):    at android.os.Handler.dispatchMessage(Handler.java:102)
2016-01-20 09:23:52:W/System.err(23600):    at android.os.Looper.loop(Looper.java:135)
2016-01-20 09:23:52:W/System.err(23600):    at android.app.ActivityThread.main(ActivityThread.java:5300)
2016-01-20 09:23:52:W/System.err(23600):    at java.lang.reflect.Method.invoke(Native Method)
2016-01-20 09:23:52:W/System.err(23600):    at java.lang.reflect.Method.invoke(Method.java:372)
2016-01-20 09:23:52:W/System.err(23600):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
2016-01-20 09:23:52:W/System.err(23600):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
