### ISSUE TITLE
histogram fails, on xperia Z 

### ISSUE THREAD

**Issue by troop** [troop/FreeDcam#4]
java.lang.NullPointerException
at com.troop.freedcam.ui.HistogramFragment.strtLsn(HistogramFragment.java:132)
at com.troop.freedcam.ui.MainActivity_v2.ShowHistogram(MainActivity_v2.java:573)
at com.troop.freedcam.ui.menu.themes.classic.menu.childs.ExpandAbleChildHistogram.onCheckedChanged(ExpandAbleChildHistogram.java:52)
at android.widget.CompoundButton.setChecked(CompoundButton.java:127)
at android.widget.Switch.setChecked(Switch.java:666)
at android.widget.CompoundButton.toggle(CompoundButton.java:87)
at android.widget.CompoundButton.performClick(CompoundButton.java:99)
at android.view.View$PerformClick.run(View.java:18570)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:212)
at android.app.ActivityThread.main(ActivityThread.java:5135)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:878)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
at dalvik.system.NativeStart.main(Native Method)

**Comment by troop** [comment]
fails on m9 too it seems
