### ISSUE TITLE
App crashes when selecting Raw10 or Raw_sensor modes

### ISSUE THREAD

**Issue by rancidfrog** [troop/FreeDcam#47]
Options given: Jpeg, raw10, raw_sensor
When either of the two raw options are selected the app crashes, then it crashes immediately when trying to reopen app, ( empty debug log). Forcing uninstall and reinstall to get it to work again.

AOSP z3 compact

**Comment by rancidfrog** [comment]
```
11.59.23:(D) freedcam.MainActivityloading cameraWrapper
11.59.23:(D) freedcam.MainActivityloaded cameraWrapper
11.59.23:(D) freedcam.CameraUiWrapperApi2Constructor done
11.59.23:(D) AbstractCameraFragmentonCreateView
11.59.23:(D) freedcam.MainActivityadd events
11.59.23:(D) freedcam.LifeCycleActivity onResume
11.59.23:(D) CameraUiFragment####################ONCREATEDVIEW####################
11.59.23:(D) ThumbViewLoad Thumb IMG_2016.03.23_23.58.00.jpg
11.59.23:(D) CameraUiFragment####################VIEW CREATED####################
11.59.23:(D) ShutterButtonModule Changed
11.59.23:(D) ShutterButtonSet wrapper to ShutterButton
11.59.23:(D) RotatingSeekbarsetprogres3
11.59.23:(D) SettingsMenuFragmentonviewCreated
11.59.23:(D) ScreenSlidePagerAdapterreadFiles sucess, FilesCount2
11.59.23:(D) SettingsMenuFragmentonResume
11.59.23:(D) SettingsmenuFragmentset CameraWrapper
11.59.23:(D) freedcam.ParameterHandlerApi2Set Orientation to:90
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.camera2.CaptureRequest$Builder.set(android.hardware.camera2.CaptureRequest$Key, java.lang.Object)' on a null object reference
	at com.troop.freedcam.camera2.parameters.ParameterHandlerApi2.SetPictureOrientation(ParameterHandlerApi2.java:187)
	at com.troop.freedcam.MainActivity.OrientationChanged(MainActivity.java:330)
	at com.troop.freedcam.ui.menu.OrientationHandler$1.onOrientationChanged(OrientationHandler.java:34)
	at android.view.OrientationEventListener$SensorEventListenerImpl.onSensorChanged(OrientationEventListener.java:143)
	at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:481)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:323)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5453)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11.59.23:(D) freedcam.CameraUiWrapperApi2SurfaceTextureAvailable
11.59.23:(D) freedcam.BaseCameraHolderApi2Open Camera
11.59.23:(D) ViewfinderProcessorCtor
11.59.23:(D) freedcam.CameraUiWrapperApi2opencamera
11.59.23:(D) ShutterButtonswitchBackground:image_capture_stopped
11.59.23:(D) ContrastisSupported:false
11.59.23:(D) BurstisSupported:false
11.59.23:(D) BrightnessisSupported:false
11.59.23:(D) WBisSupported:false
11.59.23:(D) ConvergenceisSupported:false
11.59.23:(D) ExposureisSupported:false
11.59.23:(D) FXisSupported:false
11.59.23:(D) MFisSupported:false
11.59.23:(D) SaturationisSupported:false
11.59.23:(D) SharpnessisSupported:false
11.59.23:(D) ShutterisSupported:false
11.59.23:(D) ISOisSupported:false
11.59.23:(D) ZoomisSupported:false
11.59.23:(D) f-numisSupported:false
11.59.23:(D) SkintoneisSupported:false
11.59.23:(D) ProgramShiftisSupported:false
11.59.23:(D) freedcam.LifeCycleFocus has changed!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!true
11.59.24:(D) freedcam.BaseCameraHolderApi2Camera open
11.59.24:(D) freedcam.ParameterHandlerApi2android.blackLevel.lock
11.59.24:(D) freedcam.ParameterHandlerApi2android.colorCorrection.aberrationMode
11.59.24:(D) freedcam.ParameterHandlerApi2android.colorCorrection.gains
11.59.24:(D) freedcam.ParameterHandlerApi2android.colorCorrection.mode
11.59.24:(D) freedcam.ParameterHandlerApi2android.colorCorrection.transform
11.59.24:(D) freedcam.ParameterHandlerApi2android.control.aeAntibandingMode
11.59.24:(D) freedcam.ParameterHandlerApi2android.control.aeExposureCompensation
11.59.24:(D) freedcam.ParameterHandlerApi2android.control.aeLock
11.59.24:(D) freedcam.ParameterHandlerApi2android.control.aeMode
11.59.24:(D) freedcam.ParameterHandlerApi2android.control.aePrecaptureTrigger
11.59.24:(D) freedcam.ParameterHandlerApi2android.control.aeRegions
11.59.24:(D) freedcam.ParameterHandlerApi2android.control.aeTargetFpsRange
11.59.24:(D) freedcam.ParameterHandlerApi2android.control.afMode
11.59.24:(D) freedcam.ParameterHandlerApi2android.control.afRegions
11.59.24:(D) freedcam.ParameterHandlerApi2android.control.afTrigger
11.59.24:(D) freedcam.ParameterHandlerApi2android.control.awbLock
11.59.24:(D) freedcam.ParameterHandlerApi2android.control.awbMode
11.59.24:(D) freedcam.ParameterHandlerApi2android.control.captureIntent
11.59.24:(D) freedcam.ParameterHandlerApi2android.control.effectMode
11.59.24:(D) freedcam.ParameterHandlerApi2android.control.mode
11.59.24:(D) freedcam.ParameterHandlerApi2android.control.sceneMode
11.59.24:(D) freedcam.ParameterHandlerApi2android.control.videoStabilizationMode
11.59.24:(D) freedcam.ParameterHandlerApi2android.edge.mode
11.59.24:(D) freedcam.ParameterHandlerApi2android.flash.mode
11.59.24:(D) freedcam.ParameterHandlerApi2android.hotPixel.mode
11.59.24:(D) freedcam.ParameterHandlerApi2android.jpeg.gpsLocation
11.59.24:(D) freedcam.ParameterHandlerApi2android.jpeg.orientation
11.59.24:(D) freedcam.ParameterHandlerApi2android.jpeg.quality
11.59.24:(D) freedcam.ParameterHandlerApi2android.jpeg.thumbnailQuality
11.59.24:(D) freedcam.ParameterHandlerApi2android.jpeg.thumbnailSize
11.59.24:(D) freedcam.ParameterHandlerApi2android.lens.aperture
11.59.24:(D) freedcam.ParameterHandlerApi2android.lens.filterDensity
11.59.24:(D) freedcam.ParameterHandlerApi2android.lens.focalLength
11.59.24:(D) freedcam.ParameterHandlerApi2android.lens.focusDistance
11.59.24:(D) freedcam.ParameterHandlerApi2android.lens.opticalStabilizationMode
11.59.24:(D) freedcam.ParameterHandlerApi2android.noiseReduction.mode
11.59.24:(D) freedcam.ParameterHandlerApi2android.scaler.cropRegion
11.59.24:(D) freedcam.ParameterHandlerApi2android.sensor.exposureTime
11.59.24:(D) freedcam.ParameterHandlerApi2android.sensor.frameDuration
11.59.24:(D) freedcam.ParameterHandlerApi2android.sensor.sensitivity
11.59.24:(D) freedcam.ParameterHandlerApi2android.shading.mode
11.59.24:(D) freedcam.ParameterHandlerApi2android.statistics.faceDetectMode
11.59.24:(D) freedcam.ParameterHandlerApi2android.statistics.hotPixelMapMode
11.59.24:(D) freedcam.ParameterHandlerApi2android.statistics.lensShadingMapMode
11.59.24:(D) freedcam.ParameterHandlerApi2android.tonemap.curve
11.59.24:(D) freedcam.ParameterHandlerApi2android.tonemap.mode
11.59.24:(D) ManualExposureTimeApi2max exposuretime:1026625560
11.59.24:(D) ManualExposureTimeApi2min exposuretime:17571
11.59.24:(D) ManualExposureTimeApi2max exposuretime:1026625560
11.59.24:(D) ManualExposureTimeApi2min exposuretime:17571
11.59.24:(D) ManualExposureTimeApi2max exposuretime:1026625560
11.59.24:(D) ManualExposureTimeApi2min exposuretime:17571
11.59.24:(D) VideoMediaProfileCustomMediaProfile exists loading....
11.59.24:(D) VideoMediaProfileProfileName:Timelapse480pDuration:30FileFormat:2Quality:1004
11.59.24:(D) VideoMediaProfileABR:96000AChannels:1Acodec:3AsampleRate48000audio_active:false
11.59.24:(D) VideoMediaProfileVBitrate:6000000VCodec:2VFrameRate:30VWidth:720Vheight:480
11.59.24:(D) VideoMediaProfileProfileName:720pDuration:30FileFormat:2Quality:5
11.59.24:(D) VideoMediaProfileABR:96000AChannels:1Acodec:3AsampleRate48000audio_active:true
11.59.24:(D) VideoMediaProfileVBitrate:12000000VCodec:2VFrameRate:30VWidth:1280Vheight:720
11.59.24:(D) VideoMediaProfileProfileName:Timelapse720pDuration:30FileFormat:2Quality:1005
11.59.24:(D) VideoMediaProfileABR:96000AChannels:1Acodec:3AsampleRate48000audio_active:false
11.59.24:(D) VideoMediaProfileVBitrate:12000000VCodec:2VFrameRate:30VWidth:1280Vheight:720
11.59.24:(D) VideoMediaProfileProfileName:480pDuration:30FileFormat:2Quality:4
11.59.24:(D) VideoMediaProfileABR:96000AChannels:1Acodec:3AsampleRate48000audio_active:true
11.59.24:(D) VideoMediaProfileVBitrate:6000000VCodec:2VFrameRate:30VWidth:640Vheight:480
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.hardware.camera2.CameraCaptureSession.setRepeatingRequest(android.hardware.camera2.CaptureRequest, android.hardware.camera2.CameraCaptureSession$CaptureCallback, android.os.Handler)' on a null object reference
	at com.troop.freedcam.camera2.parameters.manual.ManualExposureApi2.SetValue(ManualExpo
```

**Comment by troop** [comment]
its confusing.
```
11.59.24:(D) freedcam.ParameterHandlerApi2android.tonemap.mode
11.59.24:(D) ManualExposureTimeApi2max exposuretime:1026625560
11.59.24:(D) ManualExposureTimeApi2min exposuretime:17571
11.59.24:(D) ManualExposureTimeApi2max exposuretime:1026625560
11.59.24:(D) ManualExposureTimeApi2min exposuretime:17571
11.59.24:(D) ManualExposureTimeApi2max exposuretime:1026625560
11.59.24:(D) ManualExposureTimeApi2min exposuretime:17571 
```
there it can access the manualexpotime, then its null hmhmhmhm
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.hardware.camera2.CameraCaptureSession.setRepeatingRequest(android.hardware.camera2.CaptureRequest, android.hardware.camera2.CameraCaptureSession$CaptureCallback, android.os.Handler)' on a null object reference
    at com.troop.freedcam.camera2.parameters.manual.ManualExposureApi2.SetValue(ManualExpo
```

for me it looks like the camera dies while starting. but i cant reproduce the problem. g4 nexus5 works.
maybe you can attach a full log wich contains also native debug stuff. but you must create that logs with android studio

**Comment by rancidfrog** [comment]
It might be camera driver issue as it is under development.
Only issue is that if the change is made app becomes unusable, and crashes instantly on launch.
The only way to fix selection is to uninstall and reinstall.
Instead of FC, pop up error and keep it jpeg as raw not yet supported I guess

**Comment by troop** [comment]
Normaly you see the raw formats only when its supported. Could be a temporary bug from os hal. When i rember correct raw was working bevor jpeg did work.

**Comment by troop** [comment]
did something happen on that problem?

**Comment by rancidfrog** [comment]
Just tested with latest beta.
JPEG and bayer are the options. No crashes.
The jpeg works, bayer seems to work but not able to view them since settings might be off (not sure which options to select in Viewer raw2dng) and again also due to camera blobs not working properly with new kernel branch.
```
Xperia z3c
3.10.84-g499d8e1
ae-bracket-hdr-values=Off,AE-Bracket
ae-bracket-hdr=Off
antibanding-values=off,60hz,50hz,auto
antibanding=off
auto-exposure-lock-supported=true
auto-exposure-lock=false
auto-exposure-values=frame-average,center-weighted,spot-metering,center-weighted,spot-metering-adv,center-weighted-adv
auto-exposure=frame-average
auto-hdr-enable=disable
auto-hdr-supported=true
auto-whitebalance-lock-supported=true
auto-whitebalance-lock=false
avtimer=disable
brightness-step=1
cache-video-buffers=disable
camera-mode=0
capture-burst-interval=1
capture-burst-queue-depth=2
capture-burst-retroactive=2
cds-mode-values=off,on,auto
cds-mode=on
chroma-flash-values=chroma-flash-off,chroma-flash-on
chroma-flash=chroma-flash-off
contrast-step=1
contrast=5
cur-exposure-time=131.783113
cur-focus-diopter=0.130024
cur-focus-scale=60
cur-iso=800
denoise-values=denoise-off,denoise-on
denoise=denoise-on
dis-values=enable,disable
dis=disable
effect-values=none,mono,negative,solarize,sepia,posterize,whiteboard,blackboard,aqua,emboss,sketch,neon
effect=none
exposure-compensation-step=0.166667
exposure-compensation=0
exposure-time=0
face-detection-values=off,on
face-detection=off
flash-mode-values=off,auto,on,torch
flash-mode=off
flip-mode-values=off,flip-v,flip-h,flip-vh
focal-length=4.2
focus-areas=(66,27,362,472,1000)
focus-distances=Infinity,Infinity,Infinity
focus-mode-values=auto,infinity,fixed,macro,continuous-video,continuous-picture,manual
focus-mode=auto
hdr-mode-values=hdr-mode-sensor,hdr-mode-multiframe
hdr-mode=hdr-mode-multiframe
hdr-need-1x-values=false,true
hdr-need-1x=false
hfr-size-values=3840x2160
histogram-values=enable,disable
histogram=disable
horizontal-view-angle=68.4
instant-aec=0
instant-capture=0
internal-restart=true
iso-values=auto,ISO_HJR,ISO100,ISO200,ISO400,ISO800,ISO1600,ISO3200
iso=auto
jpeg-quality=85
jpeg-thumbnail-height=288
jpeg-thumbnail-quality=85
jpeg-thumbnail-size-values=512x288,480x288,256x154,432x288,320x320,320x240,176x144,240x320,144x176,0x0
jpeg-thumbnail-width=512
lensshade-values=enable,disable
lensshade=enable
long-shot=off
longshot-supported=true
luma-adaptation=3
manual-exposure-modes=off,exp-time-priority,iso-priority,user-setting
manual-focus-modes=off,scale-mode,diopter-mode
manual-wb-gains=1.173284,1.000000,3.105753
manual-wb-modes=off,color-temperature,rbgb-gains
max-brightness=6
max-contrast=10
max-exposure-compensation=12
max-exposure-time=1026.625560
max-focus-pos-dac=1023
max-focus-pos-diopter=10
max-focus-pos-index=1023
max-focus-pos-ratio=100
max-iso=4800
max-num-detected-faces-hw=5
max-num-detected-faces-sw=5
max-num-focus-areas=1
max-num-metering-areas=5
max-saturation=10
max-sce-factor=100
max-sharpness=36
max-wb-cct=8000
max-wb-gain=4
max-zoom=90
mce-values=enable,disable
mce=enable
metering-areas=(0, 0, 0, 0, 0)
min-brightness=0
min-contrast=0
min-exposure-compensation=-12
min-exposure-time=0.018222
min-focus-pos-dac=0
min-focus-pos-diopter=0
min-focus-pos-index=0
min-focus-pos-ratio=0
min-iso=50
min-saturation=0
min-sce-factor=-100
min-sharpness=0
min-wb-cct=2000
min-wb-gain=1
num-retro-burst-per-shutter=0
num-snaps-per-shutter=1
picture-format-values=jpeg,bayer-mipi-10gbrg,bayer-mipi-10grbg,bayer-mipi-10rggb,bayer-mipi-10bggr,yuv422sp,bayer-mipi-12gbrg,bayer-mipi-12grbg,bayer-mipi-12rggb,bayer-mipi-12bggr
picture-format=bayer-mipi-10gbrg
picture-size-values=5248x3936,4608x3456,4160x3120,4000x3000,3840x2160,3264x2448,3200x2400,2976x2976,2592x1944,2688x1512,2048x1536,1920x1080,1600x1200,1440x1080,1280x960,1280x768,1280x720,1024x768,800x600,864x480,800x480,720x480,640x480,640x360,480x360,352x288,320x240,176x144,160x120
picture-size=5248x3936
preferred-preview-size-for-video=1280x720
preview-flip=off
preview-format-values=yuv420sp,yuv420p,nv12-venus
preview-format=yuv420sp
preview-fps-range-values=(7000,7000),(7000,15000),(15000,15000),(7000,24000),(24000,24000),(7000,30000),(30000,30000)
preview-fps-range=7000,30000
preview-frame-rate-values=7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30
preview-frame-rate=30
preview-size-values=1280x720,864x480,800x480,768x432,720x480,640x640,640x480,480x640,640x360,576x432,480x360,480x320,384x288,352x288,320x240,240x320,240x160,176x144,144x176,160x120
preview-size=720x480
qc-camera-features=4828671
qc-max-num-requested-faces=5
raw-size=5248x3936
rdi-mode-values=enable,disable
rdi-mode=disable
re-focus-values=re-focus-off,re-focus-on
re-focus=re-focus-off
redeye-reduction-values=enable,disable
redeye-reduction=disable
rotation=0
saturation-step=1
saturation=5
sce-factor-step=10
scene-detect-values=off,on
scene-detect=off
scene-mode-values=auto,asd,landscape,snow,beach,sunset,night,portrait,backlight,sports,steadyphoto,flowers,candlelight,fireworks,party,night-portrait,theatre,action,AR,hdr
scene-mode=auto
scene-selection=disable
secure-mode-values=enable,disable
secure-mode=disable
selectable-zone-af-values=auto,spot-metering,center-weighted,frame-average
selectable-zone-af=auto
sensor-hdr-values=off,on
sensor-hdr=off
sharpness-step=6
sharpness=12
skinToneEnhancement-values=enable,disable
skinToneEnhancement=0
smooth-zoom-supported=false
snapshot-burst-num=1
snapshot-fd-data-enable=0
snapshot-picture-flip=off
still-more-values=still-more-off,still-more-on
still-more=still-more-off
supported-live-snapshot-sizes=3840x2160,2592x1944,2048x1536,2048x1080,1920x1080,1600x1200,1440x1080,1280x960,1280x768,1280x720,1024x768,800x600,864x480,800x480,720x480,640x480,640x360,352x288,320x240,176x144,160x120
tintless=enable
tnr-mode-values=off,on
touch-af-aec-values=touch-off,touch-on
touch-af-aec=touch-off
true-portrait-values=true-portrait-off,true-portrait-on
vertical-view-angle=50.9
video-batch-size=0
video-cds-mode-values=off,on,auto
video-flip=off
video-frame-format=yuv420sp
video-hdr-values=off,on
video-hdr=off
video-hfr-values=60,off
video-hfr=off
video-hsr=off
video-rotation-values=0,90,180,270
video-rotation=0
video-size-values=4096x2160,3840x2160,1920x1080,1280x960,1280x720,864x480,800x480,720x480,640x480,480x640,640x360,480x360,480x320,352x288,320x240,240x320,176x144,144x176,160x120
video-size=4096x2160
video-snapshot-supported=true
video-stabilization-supported=false
video-tnr-mode-values=off,on
wb-manual-cct=2471
whitebalance-values=auto,incandescent,fluorescent,warm-fluorescent,daylight,cloudy-daylight,twilight,shade,manual
whitebalance=auto
zoom-ratios=100,102,104,107,109,112,114,117,120,123,125,128,131,135,138,141,144,148,151,155,158,162,166,170,174,178,182,186,190,195,200,204,209,214,219,224,229,235,240,246,251,257,263,270,276,282,289,296,303,310,317,324,332,340,348,356,364,373,381,390,400,409,418,428,438,448,459,470,481,492,503,515,527,540,552,565,578,592,606,620,634,649,664,680,696,712,729,746,763,781,800
zoom-supported=true
zoom=0
zsl-burst-led-on-period=300
zsl-hdr-supported=true
zsl-values=off,on
zsl=off
```

**Comment by troop** [comment]
so they switched to camera1 api. 
getting raw to dng converting is not a big problem.
pls attach a bayer-mipi10 and if it works a bayer-mipi12
but i dont expect that 12bit raw works.

**Comment by rancidfrog** [comment]
Sorry for the lack of feedback, but sony dev keep switching things around. I was waiting for more stable camera but does not seem to come.
They switched back to camera2 api, but camera1 api still available with FreeDCaM, and camera1 is more stable: https://github.com/sonyxperiadev/camera/issues/47
Camera1 API bayer format is available and seems to work, saves and can be viewed using desktop image viewer, (FreeDCam viewer does not seem to work) but .bayer files  1.1 -1.2mb.
Camera2 API raw_sensor and raw10 appear but selecting them causes the same FC and App keeps FC on start unless data cache cleared which reverts raw selection.
```
01-01 22:17:10.319   438  4238 D FocuspeakProcessorApi2: kill()
01-01 22:17:10.319   438  4238 D Camera2Fragment: Start Preview
01-01 22:17:10.319   438  4238 D PictureModuleApi2: Start Preview
01-01 22:17:10.320   438  4238 D PictureModuleApi2: ImageReader RAW_SENOSR
01-01 22:17:10.320   438  4238 D AndroidRuntime: Shutting down VM
01-01 22:17:10.321   438  4238 E AndroidRuntime: FATAL EXCEPTION: main
01-01 22:17:10.321   438  4238 E AndroidRuntime: Process: troop.com.freedcam, PID: 4238
01-01 22:17:10.321   438  4238 E AndroidRuntime: java.util.NoSuchElementException
01-01 22:17:10.321   438  4238 E AndroidRuntime: 	at java.util.AbstractList$Itr.next(AbstractList.java:364)
01-01 22:17:10.321   438  4238 E AndroidRuntime: 	at java.util.Collections.max(Collections.java:781)
01-01 22:17:10.321   438  4238 E AndroidRuntime: 	at freed.cam.apis.camera2.modules.PictureModuleApi2.startPreview(PictureModuleApi2.java:868)
01-01 22:17:10.321   438  4238 E AndroidRuntime: 	at freed.cam.apis.camera2.Camera2Fragment.StartPreview(Camera2Fragment.java:121)
01-01 22:17:10.321   438  4238 E AndroidRuntime: 	at freed.cam.apis.camera2.parameters.manual.BurstApi2$1.run(BurstApi2.java:105)
01-01 22:17:10.321   438  4238 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
01-01 22:17:10.321   438  4238 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-01 22:17:10.321   438  4238 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
01-01 22:17:10.321   438  4238 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6077)
01-01 22:17:10.321   438  4238 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-01 22:17:10.321   438  4238 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
01-01 22:17:10.321   438  4238 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
01-01 22:17:10.322   438  2847 I am_crash: [4238,0,troop.com.freedcam,949534278,java.util.NoSuchElementException,NULL,AbstractList.java,364]
```
```
01-01 22:18:48.021   438  4902 E AndroidRuntime: FATAL EXCEPTION: main
01-01 22:18:48.021   438  4902 E AndroidRuntime: Process: troop.com.freedcam, PID: 4902
01-01 22:18:48.021   438  4902 E AndroidRuntime: java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 1, found: 20 Pager id: troop.com.freedcam:id/pager Pager class: class android.support.v4.view.ViewPager Problematic adapter: class freed.viewer.screenslide.ScreenSlideFragment$ScreenSlidePagerAdapter
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1171)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1120)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1646)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.view.View.measure(View.java:19733)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.view.View.measure(View.java:19733)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1662)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.view.View.measure(View.java:19733)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.view.View.measure(View.java:19733)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.view.View.measure(View.java:19733)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.view.View.measure(View.java:19733)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.view.View.measure(View.java:19733)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.view.View.measure(View.java:19733)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:687)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.view.View.measure(View.java:19733)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2271)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1358)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1607)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6307)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:683)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:619)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6077)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
01-01 22:18:48.021   438  4902 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
01-01 22:18:48.022   438  3508 I am_on_resume_called: [0,com.android.packageinstaller.permission.ui.GrantPermissionsActivity,LAUNCH_ACTIVITY]
01-01 22:18:48.023   438  2847 I am_crash: [4902,0,troop.com.freedcam,949534278,java.lang.IllegalStateException,The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 1, found: 20 Pager id: troop.com.freedcam:id/pager Pager class: class android.support.v4.view.ViewPager Problematic adapter: class freed.viewer.screenslide.ScreenSlideFragment$ScreenSlidePagerAdapter,ViewPager.java,1171]
```

**Comment by troop** [comment]
For a 16mp senosor raw should be around 19mb with 10bit. Around 30mb with 16bit. Around 1mb its a jpeg. Rename.bayer to .jpg and you will see
