### ISSUE TITLE
Crash after Permission requests on first launch

### ISSUE THREAD

**Issue by rancidfrog** [troop/FreeDcam#66]
3.3.133beta1:
After granting permissions on first run app crashes:
http://hastebin.com/izajagiyoj.coffee

**Comment by rancidfrog** [comment]
Also,
```
--------- beginning of crash
05-23 18:46:03.475 E/AndroidRuntime(18394): FATAL EXCEPTION: main
05-23 18:46:03.475 E/AndroidRuntime(18394): Process: troop.com.freedcam, PID: 18394
05-23 18:46:03.475 E/AndroidRuntime(18394): Theme: themes:{}
05-23 18:46:03.475 E/AndroidRuntime(18394): java.lang.RuntimeException: Unable to destroy activity {troop.com.freedcam/com.freedcam.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.BufferedWriter.close()' on a null object reference
05-23 18:46:03.475 E/AndroidRuntime(18394): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3859)
05-23 18:46:03.475 E/AndroidRuntime(18394): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3877)
05-23 18:46:03.475 E/AndroidRuntime(18394): 	at android.app.ActivityThread.-wrap5(ActivityThread.java)
05-23 18:46:03.475 E/AndroidRuntime(18394): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1401)
05-23 18:46:03.475 E/AndroidRuntime(18394): 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-23 18:46:03.475 E/AndroidRuntime(18394): 	at android.os.Looper.loop(Looper.java:148)
05-23 18:46:03.475 E/AndroidRuntime(18394): 	at android.app.ActivityThread.main(ActivityThread.java:5458)
05-23 18:46:03.475 E/AndroidRuntime(18394): 	at java.lang.reflect.Method.invoke(Native Method)
05-23 18:46:03.475 E/AndroidRuntime(18394): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
05-23 18:46:03.475 E/AndroidRuntime(18394): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
05-23 18:46:03.475 E/AndroidRuntime(18394): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.BufferedWriter.close()' on a null object reference
05-23 18:46:03.475 E/AndroidRuntime(18394): 	at com.freedcam.utils.AppSettingsManager.SaveAppSettings(AppSettingsManager.java:324)
05-23 18:46:03.475 E/AndroidRuntime(18394): 	at com.AbstractFragmentActivity.onDestroy(AbstractFragmentActivity.java:62)
05-23 18:46:03.475 E/AndroidRuntime(18394): 	at com.freedcam.MainActivity.onDestroy(MainActivity.java:105)
05-23 18:46:03.475 E/AndroidRuntime(18394): 	at android.app.Activity.performDestroy(Activity.java:6422)
05-23 18:46:03.475 E/AndroidRuntime(18394): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1142)
05-23 18:46:03.475 E/AndroidRuntime(18394): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3846)
05-23 18:46:03.475 E/AndroidRuntime(18394): 	... 9 more
05-23 18:46:06.221 W/InputMethodManagerService(883): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@905d4f3 attribute=null, token = android.os.BinderProxy@919e2d4
05-23 18:46:06.242 I/WindowState(883): WIN DEATH: Window{acf3ab4 u0 troop.com.freedcam/com.freedcam.MainActivity}
```
