### ISSUE TITLE
mi4c, force closes on startup with Mokee rom.

### ISSUE THREAD

**Issue by Sinaaaa** [troop/FreeDcam#73]
Crash file generated by freedcam:

java.lang.RuntimeException: Unable to start activity ComponentInfo{troop.com.freedcam/com.freedcam.MainActivity}: android.renderscript.RSRuntimeException: Loading of ScriptC script failed.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: android.renderscript.RSRuntimeException: Loading of ScriptC script failed.
	at android.renderscript.ScriptC.<init>(ScriptC.java:63)
	at com.freedcam.apis.camera2.camera.renderscript.ScriptC_focus_peak.<init>(ScriptC_focus_peak.java:42)
	at com.freedcam.apis.camera2.camera.renderscript.ScriptC_focus_peak.<init>(ScriptC_focus_peak.java:34)
	at com.freedcam.utils.RenderScriptHandler.<init>(RenderScriptHandler.java:38)
	at com.freedcam.MainActivity.createHandlers(MainActivity.java:162)
	at com.freedcam.MainActivity.onCreate(MainActivity.java:83)
	at android.app.Activity.performCreate(Activity.java:6251)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
	... 9 more

**Comment by troop** [comment]
looks for me like a cm based rom. that can have problems with renderscript.
but i did not see it for a long time. try to clear cache and start then again freedcam

**Comment by Sinaaaa** [comment]
Tried, did not work :( ah well gotta juggle roms some more.
