### ISSUE TITLE
huawei P9 无法运行(Unable to start)

### ISSUE THREAD

**Issue by toutoumu** [troop/FreeDcam#94]
07-28 15:53:39.264 23324-23398/troop.com.freedcam E/RenderScript: Unable to open shared library (/data/user/0/troop.com.freedcam/code_cache/com.android.renderscript.cache/librs.focuspeak_argb.so): undefined symbol: init

07-28 11:09:12.447 19272-19272/? W/VRSystemServiceManager: vr state query exception!
                                                           android.os.DeadObjectException
                                                               at android.os.BinderProxy.transactNative(Native Method)
                                                               at android.os.BinderProxy.transact(Binder.java:505)
                                                               at android.vrsystem.IVRSystemService$Stub$Proxy.isVRmode(IVRSystemService.java:120)
                                                               at android.vrsystem.VRSystemServiceManager.isVRMode(VRSystemServiceManager.java:63)
                                                               at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:88)
                                                               at com.android.systemui.SystemUiUtil.addWindowView(SystemUiUtil.java:404)
                                                               at com.android.systemui.statusbar.BaseStatusBar.updateSearchPanel(BaseStatusBar.java:964)
                                                               at com.android.systemui.statusbar.phone.PhoneStatusBar.updateSearchPanel(PhoneStatusBar.java:1076)
                                                               at com.android.systemui.statusbar.phone.PhoneStatusBar.prepareNavigationBarView(PhoneStatusBar.java:1292)
                                                               at com.android.systemui.statusbar.phone.PhoneStatusBar.repositionNavigationBar(PhoneStatusBar.java:1314)
                                                               at com.android.systemui.statusbar.phone.HwPhoneStatusBar.handlIntent(HwPhoneStatusBar.java:292)
                                                               at com.android.systemui.statusbar.phone.PhoneStatusBar.-wrap1(PhoneStatusBar.java)
                                                               at com.android.systemui.statusbar.phone.PhoneStatusBar$15.onReceive(PhoneStatusBar.java:3682)
                                                               at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:966)
                                                               at android.os.Handler.handleCallback(Handler.java:743)
                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                               at android.os.Looper.loop(Looper.java:150)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5643)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)
07-28 11:09:12.453 19272-19272/? W/VRSystemServiceManager: vr state query exception!
                                                           android.os.DeadObjectException
                                                               at android.os.BinderProxy.transactNative(Native Method)
                                                               at android.os.BinderProxy.transact(Binder.java:505)
                                                               at android.vrsystem.IVRSystemService$Stub$Proxy.isVRmode(IVRSystemService.java:120)
                                                               at android.vrsystem.VRSystemServiceManager.isVRMode(VRSystemServiceManager.java:63)
                                                               at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:88)
                                                               at com.android.systemui.assist.AssistManager.onConfigurationChanged(AssistManager.java:119)
                                                               at com.android.systemui.statusbar.phone.PhoneStatusBar.prepareNavigationBarView(PhoneStatusBar.java:1293)
                                                               at com.android.systemui.statusbar.phone.PhoneStatusBar.repositionNavigationBar(PhoneStatusBar.java:1314)
                                                               at com.android.systemui.statusbar.phone.HwPhoneStatusBar.handlIntent(HwPhoneStatusBar.java:292)
                                                               at com.android.systemui.statusbar.phone.PhoneStatusBar.-wrap1(PhoneStatusBar.java)
                                                               at com.android.systemui.statusbar.phone.PhoneStatusBar$15.onReceive(PhoneStatusBar.java:3682)
                                                               at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:966)
                                                               at android.os.Handler.handleCallback(Handler.java:743)
                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                               at android.os.Looper.loop(Looper.java:150)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5643)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)

**Comment by troop** [comment]
sorry but that contains nothing about freedcam

**Comment by toutoumu** [comment]
07-28 15:53:39.264 23324-23398/troop.com.freedcam E/RenderScript: Unable to open shared library (/data/user/0/troop.com.freedcam/code_cache/com.android.renderscript.cache/librs.focuspeak_argb.so): undefined symbol: init
